name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Set to your default branch name

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # This means it will upload the root folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
